// --- GÜVENLİK AYARLARI ---
const GLOBAL_SITE_PASS = "Admin123"; 

const authorizedUsers = {
    "442277": { name: "Queen Targaryen",   pass: "Queen1661" },
    "371687": { name: "Habib Targaryen",   pass: "Habib123" },
    "200328": { name: "Kayy Sarsilmaz",    pass: "Kayy123" },
    "286841": { name: "Courts Marelli",    pass: "Courts123" },
    "941":    { name: "Sully Ra'Nell",     pass: "Sully123" },
    "1001":   { name: "Test User",         pass: "1234" }
};

let currentQuestions = [];
let currentUserInfo = ""; 
let currentAdminName = ""; 
let currentCategoryName = ""; 
let selectedIndices = [];

function checkLogin() {
    const siteInput = document.getElementById('sitePassInput').value.trim();
    const idInput = document.getElementById('userIdInput').value.trim();
    const passInput = document.getElementById('userPassInput').value.trim();
    const errorMsg = document.getElementById('error-msg');
    const welcomeMsg = document.getElementById('welcome-msg');
    const loginCard = document.querySelector('#login-screen .card'); 
    
    function triggerError(msg) {
        errorMsg.innerText = msg;
        errorMsg.style.display = 'block';
        loginCard.classList.add('shake');
        setTimeout(() => loginCard.classList.remove('shake'), 500);
    }

    if (siteInput !== GLOBAL_SITE_PASS) { triggerError("Global Site Access Code is wrong!"); return; }
    if (!authorizedUsers[idInput]) { triggerError("User ID not found in database!"); return; }
    if (authorizedUsers[idInput].pass !== passInput) { triggerError("Wrong personal password!"); return; }

    currentAdminName = authorizedUsers[idInput].name;
    currentUserInfo = `${currentAdminName} (ID: ${idInput})`;
    
    errorMsg.style.display = 'none';
    welcomeMsg.innerText = `Access Granted. Welcome, ${currentAdminName}!`;
    welcomeMsg.style.display = 'block';

    setTimeout(() => {
        document.getElementById('login-screen').style.display = 'none';
        document.getElementById('main-content').style.display = 'block';
        document.getElementById('user-display').innerText = `Logged in as: ${currentUserInfo}`;
    }, 1000);
}

function logout() { location.reload(); }
function togglePassword(id) { const el = document.getElementById(id); el.type = el.type === 'password' ? 'text' : 'password'; }
document.addEventListener("keypress", function(e) { if(e.key==="Enter" && document.getElementById('login-screen').style.display!=='none') checkLogin(); });

// --- SINAV SİSTEMİ (GÜNCELLENDİ: ARTIK KATEGORİLİ SEÇİM YAPIYOR) ---

function generateExam(categoryName) {
    currentCategoryName = categoryName;
    const fileName = `questions-${categoryName.toLowerCase()}.json`;

    fetch(fileName)
        .then(res => res.json())
        .then(data => {
            // ESKİ RASTGELE KARIŞTIRMA SİLİNDİ.
            // YENİ AKILLI SEÇİCİ EKLENDİ:
            selectedIndices = getBalancedIndices(data);
            
            const selectedQuestions = selectedIndices.map(i => data[i]);
            displayExam(selectedQuestions);
            showCandidateButton();
        })
        .catch(err => console.error(err));
}

function displayExam(questions) {
    const qBox = document.getElementById('questions-box');
    const aBox = document.getElementById('answers-box');
    document.getElementById('questions-section').style.display = 'block';
    document.getElementById('answers-section').style.display = 'none';

    let qText = "", aText = "";
    questions.forEach((item, index) => {
        qText += `${index + 1}) ${item.q}\n`;
        aText += `${index + 1}) ${item.a}\n`;
    });

    qBox.textContent = qText;
    aBox.textContent = aText;
}

function showAnswers() {
    document.getElementById('answers-section').style.display = 'block';
    document.getElementById('answers-section').scrollIntoView({ behavior: 'smooth' });
}

function copyToClipboard(elementId) {
    const content = document.getElementById(elementId).innerText;
    const now = new Date().toLocaleString('en-GB', { timeZone: 'Europe/London' }); 
    let finalClip = elementId === 'questions-box' ? `🛑 EXAM GENERATION LOG 🛑\nGenerated By: ${currentUserInfo} (${currentCategoryName})\nDate: ${now} (UK Time)\n----------------------------------\n\n${content}` : content;
    navigator.clipboard.writeText(finalClip).then(() => alert("Copied!")).catch(err => console.error(err));
}

function showCandidateButton() {
    const qSection = document.getElementById('questions-section');
    if(document.getElementById('btn-candidate-link')) return;
    const btn = document.createElement('button');
    btn.id = 'btn-candidate-link';
    btn.className = 'btn btn-warning w-100 mb-2 fw-bold';
    btn.innerText = '🔗 Generate Candidate Link (15 Mins)';
    btn.onclick = generateCandidateLink;
    const copyBtn = qSection.querySelector('button[onclick^="copyToClipboard"]');
    qSection.insertBefore(btn, copyBtn);
}

// --- PRATİK VERİ GİRİŞİ ---
function generateCandidateLink() {
    
    // 1. SORU: ADAYIN CİNSİYETİ
    const genderInput = prompt("1/3 - Enter Gender:\nType 'M' for Mr.\nType 'F' for Ms.");
    if (!genderInput) return;

    let title = "Mx.";
    if (genderInput.toUpperCase() === 'M') title = "Mr.";
    if (genderInput.toUpperCase() === 'F') title = "Ms.";

    // 2. SORU: ADAYIN ADI
    const nameInput = prompt("2/3 - Enter Candidate Name:\n(e.g. John Doe)");
    if (!nameInput) return;

    // 3. SORU: ADAYIN ID NUMARASI
    const idInput = prompt("3/3 - Enter Candidate ID:\n(e.g. 12345)");
    if (!idInput) return;

    // OTOMATİK BİRLEŞTİRME: ARTIK "|" İŞARETİ VAR
    const fullCandidateString = `${nameInput} | ${idInput}`;

    // Veriyi Paketle
    const payload = {
        cat: currentCategoryName.toLowerCase(),
        indices: selectedIndices,
        time: new Date().getTime(),
        admin: currentAdminName,
        candidate: fullCandidateString,
        title: title
    };

    const jsonString = JSON.stringify(payload);
    const token = btoa(unescape(encodeURIComponent(jsonString))); 
    const baseUrl = window.location.href.substring(0, window.location.href.lastIndexOf('/'));
    const link = `${baseUrl}/exam.html?token=${token}`;

    navigator.clipboard.writeText(link).then(() => {
        alert(`✅ LINK COPIED!\n\nCandidate: ${title} ${fullCandidateString}\nAdmin: ${currentAdminName}\n\nSend this link to the candidate.`);
    });
}

// --- YENİ EKLENEN AKILLI SEÇİCİ FONKSİYONU ---
function getBalancedIndices(allQuestions) {
    // 1. İSTEDİĞİMİZ SIRALAMA (MENÜ)
    const targetOrder = [
        "Real Estate",  // 1. Soru
        "Auto",         // 2. Soru
        "Dating",       // 3. Soru
        "Work",         // 4. Soru
        "Business",     // 5. Soru
        "Rejected",     // 6. Soru (Illegal/Blacklist)
        "Other"         // 7. Soru (Random/Template)
    ];

    // 2. KUTULARI HAZIRLA (BUCKETS)
    let buckets = {
        "Real Estate": [], "Auto": [], "Dating": [], 
        "Work": [], "Business": [], "Rejected": [], "Other": []
    };

    // 3. SORULARI ANALİZ ET VE KUTULARA AT
    allQuestions.forEach((item, index) => {
        const answerText = item.a;
        let category = "Other"; // Varsayılan

        // A) Önce "Rejected" veya "Illegal" var mı?
        if (answerText.startsWith("Rejected") || answerText.toLowerCase().includes("illegal")) {
            category = "Rejected";
        } 
        // B) Değilse parantez içindeki kategoriye bak: (Auto), (Business) vb.
        else {
            const match = answerText.match(/\(([^)]+)\)$/); // Sondaki parantezi bulur
            if (match) {
                const rawCat = match[1].toLowerCase().trim();
                
                if (rawCat.includes("estate") || rawCat.includes("house")) category = "Real Estate";
                else if (rawCat.includes("auto") || rawCat.includes("vehicle") || rawCat.includes("car")) category = "Auto";
                else if (rawCat.includes("dating") || rawCat.includes("love")) category = "Dating";
                else if (rawCat.includes("work") || rawCat.includes("job")) category = "Work";
                else if (rawCat.includes("business")) category = "Business";
                else category = "Other";
            }
        }

        // İndeksi uygun kutuya at
        if (buckets[category]) {
            buckets[category].push(index);
        } else {
            buckets["Other"].push(index);
        }
    });

    // 4. HER KUTUDAN BİR TANE SEÇ
    let finalSelection = [];

    targetOrder.forEach(cat => {
        let chosenIndex;
        let bucket = buckets[cat];

        // Eğer o kategoride soru yoksa Other'dan al
        if (bucket.length === 0) bucket = buckets["Other"];

        if (bucket.length > 0) {
            const randomIndex = Math.floor(Math.random() * bucket.length);
            chosenIndex = bucket[randomIndex];
        } else {
            chosenIndex = 0; // Hiçbir şey yoksa 0. indeksi al (Çökmemesi için)
        }
        
        finalSelection.push(chosenIndex);
    });

    return finalSelection;
}
