// --- GÜVENLİK AYARLARI ---
const GLOBAL_SITE_PASS = "Admin123"; 

// Kullanıcı Listesi
// Format: "ID": { name: "İsim", pass: "Şifre" }
const authorizedUsers = {
    "442277": { name: "Queen Targaryen",   pass: "Queen1661" },
    "371687": { name: "Habib Targaryen",   pass: "Habib123" },
    "200328": { name: "Kayy Sarsilmaz",    pass: "Kayy123" },
    "286841": { name: "Courts Marelli",    pass: "Courts123" },
    "941":    { name: "Sully Ra'Nell",     pass: "Sully123" },
    "1001":   { name: "Test User",         pass: "1234" }
};
// ------------------------

let currentQuestions = [];
let currentUserInfo = ""; 
let currentCategoryName = ""; 

function checkLogin() {
    const siteInput = document.getElementById('sitePassInput').value.trim();
    const idInput = document.getElementById('userIdInput').value.trim();
    const passInput = document.getElementById('userPassInput').value.trim();
    
    const errorMsg = document.getElementById('error-msg');
    const welcomeMsg = document.getElementById('welcome-msg');
    const loginCard = document.querySelector('#login-screen .card'); 
    
    function triggerError(msg) {
        errorMsg.innerText = msg;
        errorMsg.style.display = 'block';
        loginCard.classList.add('shake');
        setTimeout(() => {
            loginCard.classList.remove('shake');
        }, 500);
    }

    // 1. KONTROL: Site Şifresi
    if (siteInput !== GLOBAL_SITE_PASS) {
        triggerError("Global Site Access Code is wrong!");
        return;
    }
    // 2. KONTROL: Kullanıcı ID
    if (!authorizedUsers[idInput]) {
        triggerError("User ID not found in database!");
        return;
    }
    // 3. KONTROL: Kişisel Şifre
    if (authorizedUsers[idInput].pass !== passInput) {
        triggerError("Wrong personal password!");
        return;
    }

    // --- GİRİŞ BAŞARILI ---
    const userName = authorizedUsers[idInput].name;
    currentUserInfo = `${userName} (ID: ${idInput})`;
    
    errorMsg.style.display = 'none';
    welcomeMsg.innerText = `Access Granted. Welcome, ${userName}!`;
    welcomeMsg.style.display = 'block';

    setTimeout(() => {
        document.getElementById('login-screen').style.display = 'none';
        document.getElementById('main-content').style.display = 'block';
        document.getElementById('user-display').innerText = `Logged in as: ${currentUserInfo}`;
    }, 1000);
}

function logout() {
    location.reload(); 
}

document.addEventListener("keypress", function(event) {
    if (event.key === "Enter") {
        if (document.getElementById('login-screen').style.display !== 'none') {
            checkLogin();
        }
    }
});

// --- SINAV SİSTEMİ ---

function generateExam(categoryName) {
    currentCategoryName = categoryName;
    const fileName = `questions-${categoryName.toLowerCase()}.json`;

    fetch(fileName)
        .then(response => {
            if (!response.ok) throw new Error("File not found");
            return response.json();
        })
        .then(data => {
            const selectedQuestions = shuffleAndSelect(data, 7);
            displayExam(selectedQuestions);
        })
        .catch(error => console.error(error));
}

function shuffleAndSelect(array, count) {
    let shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled.slice(0, count);
}

function displayExam(questions) {
    const qBox = document.getElementById('questions-box');
    const aBox = document.getElementById('answers-box');
    const qSection = document.getElementById('questions-section');
    const aSection = document.getElementById('answers-section');

    qBox.textContent = "";
    aBox.textContent = "";

    let questionText = "";
    let answerText = "";

    questions.forEach((item, index) => {
        questionText += `${index + 1}) ${item.q}\n`;
        answerText += `${index + 1}) ${item.a}\n`;
    });

    qBox.textContent = questionText;
    aBox.textContent = answerText;

    qSection.style.display = 'block';
    aSection.style.display = 'none';
}

function showAnswers() {
    document.getElementById('answers-section').style.display = 'block';
    document.getElementById('answers-section').scrollIntoView({ behavior: 'smooth' });
}

function copyToClipboard(elementId) {
    const content = document.getElementById(elementId).innerText;
    const now = new Date();
    const timeString = now.toLocaleString('en-GB'); 
    
    let finalClip = "";
    
    if (elementId === 'questions-box') {
        finalClip = `🛑 EXAM GENERATION LOG 🛑\nGenerated By: ${currentUserInfo} (${currentCategoryName})\nDate: ${timeString}\n----------------------------------\n\n${content}`;
    } else {
        finalClip = content;
    }

    navigator.clipboard.writeText(finalClip).then(() => {
        alert("Copied to clipboard with User Log!");
    }).catch(err => {
        console.error('Copy error:', err);
    });
}
