// --- GÜVENLİK AYARLARI ---
const GLOBAL_SITE_PASS = "Admin123"; 

const authorizedUsers = {
    "442277": { name: "Queen Targaryen",   pass: "Queen1661" },
    "371687": { name: "Habib Targaryen",   pass: "Habib123" },
    "200328": { name: "Kayy Sarsilmaz",    pass: "Kayy123" },
    "286841": { name: "Courts Marelli",    pass: "Courts123" },
    "941":    { name: "Sully Ra'Nell",     pass: "Sully123" },
    "1001":   { name: "Test User",         pass: "1234" }
};

let currentQuestions = [];
let currentUserInfo = ""; 
let currentAdminName = ""; 
let currentCategoryName = ""; 
let selectedIndices = [];

function checkLogin() {
    const siteInput = document.getElementById('sitePassInput').value.trim();
    const idInput = document.getElementById('userIdInput').value.trim();
    const passInput = document.getElementById('userPassInput').value.trim();
    const errorMsg = document.getElementById('error-msg');
    const welcomeMsg = document.getElementById('welcome-msg');
    const loginCard = document.querySelector('#login-screen .card'); 
    
    function triggerError(msg) {
        errorMsg.innerText = msg;
        errorMsg.style.display = 'block';
        loginCard.classList.add('shake');
        setTimeout(() => loginCard.classList.remove('shake'), 500);
    }

    if (siteInput !== GLOBAL_SITE_PASS) { triggerError("Global Site Access Code is wrong!"); return; }
    if (!authorizedUsers[idInput]) { triggerError("User ID not found in database!"); return; }
    if (authorizedUsers[idInput].pass !== passInput) { triggerError("Wrong personal password!"); return; }

    currentAdminName = authorizedUsers[idInput].name;
    currentUserInfo = `${currentAdminName} (ID: ${idInput})`;
    
    errorMsg.style.display = 'none';
    welcomeMsg.innerText = `Access Granted. Welcome, ${currentAdminName}!`;
    welcomeMsg.style.display = 'block';

    setTimeout(() => {
        document.getElementById('login-screen').style.display = 'none';
        document.getElementById('main-content').style.display = 'block';
        document.getElementById('user-display').innerText = `Logged in as: ${currentUserInfo}`;
    }, 1000);
}

function logout() { location.reload(); }
function togglePassword(id) { const el = document.getElementById(id); el.type = el.type === 'password' ? 'text' : 'password'; }
document.addEventListener("keypress", function(e) { if(e.key==="Enter" && document.getElementById('login-screen').style.display!=='none') checkLogin(); });

// --- SINAV SİSTEMİ ---

function generateExam(categoryName) {
    currentCategoryName = categoryName;
    const fileName = `questions-${categoryName.toLowerCase()}.json`;

    fetch(fileName)
        .then(res => res.json())
        .then(data => {
            const indices = Array.from({length: data.length}, (_, i) => i);
            for (let i = indices.length - 1; i > 0; i--) {
                const j = Math.floor(Math.random() * (i + 1));
                [indices[i], indices[j]] = [indices[j], indices[i]];
            }
            selectedIndices = indices.slice(0, 7);
            const selectedQuestions = selectedIndices.map(i => data[i]);
            displayExam(selectedQuestions);
            showCandidateButton();
        })
        .catch(err => console.error(err));
}

function displayExam(questions) {
    const qBox = document.getElementById('questions-box');
    const aBox = document.getElementById('answers-box');
    document.getElementById('questions-section').style.display = 'block';
    document.getElementById('answers-section').style.display = 'none';

    let qText = "", aText = "";
    questions.forEach((item, index) => {
        qText += `${index + 1}) ${item.q}\n`;
        aText += `${index + 1}) ${item.a}\n`;
    });

    qBox.textContent = qText;
    aBox.textContent = aText;
}

function showAnswers() {
    document.getElementById('answers-section').style.display = 'block';
    document.getElementById('answers-section').scrollIntoView({ behavior: 'smooth' });
}

function copyToClipboard(elementId) {
    const content = document.getElementById(elementId).innerText;
    const now = new Date().toLocaleString('en-GB', { timeZone: 'Europe/London' }); 
    let finalClip = elementId === 'questions-box' ? `🛑 EXAM GENERATION LOG 🛑\nGenerated By: ${currentUserInfo} (${currentCategoryName})\nDate: ${now} (UK Time)\n----------------------------------\n\n${content}` : content;
    navigator.clipboard.writeText(finalClip).then(() => alert("Copied!")).catch(err => console.error(err));
}

function showCandidateButton() {
    const qSection = document.getElementById('questions-section');
    if(document.getElementById('btn-candidate-link')) return;
    const btn = document.createElement('button');
    btn.id = 'btn-candidate-link';
    btn.className = 'btn btn-warning w-100 mb-2 fw-bold';
    btn.innerText = '🔗 Generate Candidate Link (15 Mins)';
    btn.onclick = generateCandidateLink;
    const copyBtn = qSection.querySelector('button[onclick^="copyToClipboard"]');
    qSection.insertBefore(btn, copyBtn);
}

// --- GÜNCELLENEN KISIM: İSİM + CİNSİYET SORAN SİSTEM ---
function generateCandidateLink() {
    // 1. İsim İste
    const candidateInput = prompt("Enter Candidate Name & ID:\n(Format: Name Surname | ID)");
    if (!candidateInput) return;

    // 2. Cinsiyet İste
    const genderInput = prompt("Enter Gender:\nType 'M' for Mr.\nType 'F' for Ms.");
    let title = "Mx.";
    if (genderInput && genderInput.toUpperCase() === 'M') title = "Mr.";
    if (genderInput && genderInput.toUpperCase() === 'F') title = "Ms.";

    // 3. Veriyi Paketle
    const payload = {
        cat: currentCategoryName.toLowerCase(),
        indices: selectedIndices,
        time: new Date().getTime(),
        admin: currentAdminName,
        candidate: candidateInput,
        title: title // Mr. veya Ms.
    };

    const jsonString = JSON.stringify(payload);
    const token = btoa(unescape(encodeURIComponent(jsonString))); 
    const baseUrl = window.location.href.substring(0, window.location.href.lastIndexOf('/'));
    const link = `${baseUrl}/exam.html?token=${token}`;

    navigator.clipboard.writeText(link).then(() => {
        alert(`✅ LINK COPIED!\n\nCandidate: ${title} ${candidateInput}\n\nSend this link.`);
    });
}
